// ISO 4217 Currency Definitions and Metadata for Mun Creations
export interface CurrencyMeta {
  code: string;
  symbol: string;
  name: string;
  country: string;
  flag: string;
  decimalPlaces: number;
}

export const CURRENCY_METADATA_LIST: CurrencyMeta[] = [
  {
    code: "INR",
    symbol: "₹",
    name: "Indian Rupee",
    country: "India",
    flag: "🇮🇳",
    decimalPlaces: 0,
  },
  {
    code: "USD",
    symbol: "$",
    name: "United States Dollar",
    country: "United States",
    flag: "🇺🇸",
    decimalPlaces: 2,
  },
  {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    flag: "🇪🇺",
    decimalPlaces: 2,
  },
  {
    code: "GBP",
    symbol: "£",
    name: "British Pound",
    country: "United Kingdom",
    flag: "🇬🇧",
    decimalPlaces: 2,
  },
  {
    code: "AED",
    symbol: "د.إ",
    name: "UAE Dirham",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    decimalPlaces: 2,
  },
  {
    code: "CAD",
    symbol: "C$",
    name: "Canadian Dollar",
    country: "Canada",
    flag: "🇨🇦",
    decimalPlaces: 2,
  },
  {
    code: "AUD",
    symbol: "A$",
    name: "Australian Dollar",
    country: "Australia",
    flag: "🇦🇺",
    decimalPlaces: 2,
  },
  {
    code: "SGD",
    symbol: "S$",
    name: "Singapore Dollar",
    country: "Singapore",
    flag: "🇸🇬",
    decimalPlaces: 2,
  },
  {
    code: "NZD",
    symbol: "NZ$",
    name: "New Zealand Dollar",
    country: "New Zealand",
    flag: "🇳🇿",
    decimalPlaces: 2,
  },
  {
    code: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    flag: "🇨🇭",
    decimalPlaces: 2,
  },
  {
    code: "JPY",
    symbol: "¥",
    name: "Japanese Yen",
    country: "Japan",
    flag: "🇯🇵",
    decimalPlaces: 0,
  },
  {
    code: "CNY",
    symbol: "¥",
    name: "Chinese Yuan",
    country: "China",
    flag: "🇨🇳",
    decimalPlaces: 2,
  },
  {
    code: "SAR",
    symbol: "﷼",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    decimalPlaces: 2,
  },
  {
    code: "QAR",
    symbol: "﷼",
    name: "Qatari Riyal",
    country: "Qatar",
    flag: "🇶🇦",
    decimalPlaces: 2,
  },
  {
    code: "KWD",
    symbol: "KD",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    flag: "🇰🇼",
    decimalPlaces: 3,
  },
  {
    code: "BHD",
    symbol: "BD",
    name: "Bahraini Dinar",
    country: "Bahrain",
    flag: "🇧🇭",
    decimalPlaces: 3,
  },
  { code: "OMR", symbol: "OMR", name: "Omani Rial", country: "Oman", flag: "🇴🇲", decimalPlaces: 3 },
  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    country: "South Africa",
    flag: "🇿🇦",
    decimalPlaces: 2,
  },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    flag: "🇧🇩",
    decimalPlaces: 2,
  },
  {
    code: "LKR",
    symbol: "Rs",
    name: "Sri Lankan Rupee",
    country: "Sri Lanka",
    flag: "🇱🇰",
    decimalPlaces: 2,
  },
  {
    code: "NPR",
    symbol: "रू",
    name: "Nepalese Rupee",
    country: "Nepal",
    flag: "🇳🇵",
    decimalPlaces: 2,
  },
  {
    code: "PKR",
    symbol: "₨",
    name: "Pakistani Rupee",
    country: "Pakistan",
    flag: "🇵🇰",
    decimalPlaces: 2,
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    flag: "🇲🇾",
    decimalPlaces: 2,
  },
  {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    country: "Thailand",
    flag: "🇹🇭",
    decimalPlaces: 2,
  },
  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    flag: "🇮🇩",
    decimalPlaces: 0,
  },
  {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    country: "Philippines",
    flag: "🇵🇭",
    decimalPlaces: 2,
  },
  {
    code: "HKD",
    symbol: "HK$",
    name: "Hong Kong Dollar",
    country: "Hong Kong",
    flag: "🇭🇰",
    decimalPlaces: 2,
  },
  {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    country: "Sweden",
    flag: "🇸🇪",
    decimalPlaces: 2,
  },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    country: "Norway",
    flag: "🇳🇴",
    decimalPlaces: 2,
  },
  {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    country: "Denmark",
    flag: "🇩🇰",
    decimalPlaces: 2,
  },
  {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    country: "Poland",
    flag: "🇵🇱",
    decimalPlaces: 2,
  },
  {
    code: "TRY",
    symbol: "₺",
    name: "Turkish Lira",
    country: "Turkey",
    flag: "🇹🇷",
    decimalPlaces: 2,
  },
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    country: "Brazil",
    flag: "🇧🇷",
    decimalPlaces: 2,
  },
  {
    code: "MXN",
    symbol: "Mex$",
    name: "Mexican Peso",
    country: "Mexico",
    flag: "🇲🇽",
    decimalPlaces: 2,
  },
  {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    country: "South Korea",
    flag: "🇰🇷",
    decimalPlaces: 0,
  },
  {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    country: "Vietnam",
    flag: "🇻🇳",
    decimalPlaces: 0,
  },
  {
    code: "EGP",
    symbol: "E£",
    name: "Egyptian Pound",
    country: "Egypt",
    flag: "🇪🇬",
    decimalPlaces: 2,
  },
  {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Shekel",
    country: "Israel",
    flag: "🇮🇱",
    decimalPlaces: 2,
  },
  {
    code: "RUB",
    symbol: "₽",
    name: "Russian Ruble",
    country: "Russia",
    flag: "🇷🇺",
    decimalPlaces: 2,
  },
];

export const CURRENCY_MAP: Record<string, CurrencyMeta> = CURRENCY_METADATA_LIST.reduce(
  (acc, item) => {
    acc[item.code] = item;
    return acc;
  },
  {} as Record<string, CurrencyMeta>,
);

export const POPULAR_CURRENCIES = [
  "USD",
  "INR",
  "EUR",
  "GBP",
  "AED",
  "CAD",
  "AUD",
  "SGD",
  "SAR",
  "QAR",
];
