// Automated acceptance test for Master CMS API & Storefront integration
const BASE_URL = "http://localhost:5173";

async function runTests() {
  console.log("=== 1. Health API Check ===");
  const healthRes = await fetch(`${BASE_URL}/api/health`);
  const health = await healthRes.json();
  console.log("Health Status:", health);

  console.log("\n=== 2. Admin Auth Login Check ===");
  const loginRes = await fetch(`${BASE_URL}/api/admin/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ password: "mun@dev1234" }),
  });
  const loginData = await loginRes.json();
  if (!loginData.success || !loginData.token) {
    throw new Error(`Login failed: ${JSON.stringify(loginData)}`);
  }
  console.log("Login Success! Token:", loginData.token.substring(0, 15) + "...");
  const token = loginData.token;
  const authHeaders = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  console.log("\n=== 3. Admin Catalog Retrieval ===");
  const catalogRes = await fetch(`${BASE_URL}/api/admin/products`, { headers: authHeaders });
  const catalog = await catalogRes.json();
  console.log(`Total Products: ${catalog.total}, Active: ${catalog.stats.active}, Drafts: ${catalog.stats.draft}, Low Stock: ${catalog.stats.lowStock}`);

  console.log("\n=== 4. Admin Add Product (Canonical Master Model) ===");
  const newProduct = {
    name: "Automated Acceptance Royal Gold Katan Saree",
    sku: `TEST-MUN-${Date.now()}`,
    category: "Banarasi",
    subcategory: "Katan Silk",
    fabric: "Pure Katan Silk",
    color: "Peacock Royal Blue",
    priceUsd: 450,
    priceInr: 37575,
    stockQuantity: 6,
    lowStockThreshold: 2,
    active: true,
    published: true,
    status: "active",
    badge: "new",
    image: "/images/products/hero-saree.webp",
    description: "Automated acceptance test product generated by CMS verification suite.",
    careInstructions: "Dry clean only. Store wrapped in muslin cloth.",
    zariType: "Pure Tested Gold Zari",
    sareeLength: "5.5m + 0.8m blouse",
    loomOrigin: "Varanasi Heritage Looms (GI Tagged)",
    weight: "800g",
    seoTitle: "Royal Blue Katan Banarasi Silk Saree",
    seoDescription: "Authentic royal blue handwoven Banarasi saree.",
  };

  const createRes = await fetch(`${BASE_URL}/api/admin/products`, {
    method: "POST",
    headers: authHeaders,
    body: JSON.stringify(newProduct),
  });
  const createData = await createRes.json();
  if (!createData.success || !createData.product) {
    throw new Error(`Create product failed: ${JSON.stringify(createData)}`);
  }
  const createdProd = createData.product;
  console.log(`Created Saree ID: ${createdProd.id}, SKU: ${createdProd.sku}, Slug: ${createdProd.slug}`);

  console.log("\n=== 5. Public Storefront Integration Check ===");
  const pubRes = await fetch(`${BASE_URL}/api/products?search=${encodeURIComponent(createdProd.sku)}`);
  const pubList = await pubRes.json();
  const foundOnStorefront = pubList.some((p) => p.id === createdProd.id || p.sku === createdProd.sku);
  console.log("Product Immediately Available on Storefront API:", foundOnStorefront);

  console.log("\n=== 6. Single Product by Slug Check ===");
  const slugRes = await fetch(`${BASE_URL}/api/products/slug/${encodeURIComponent(createdProd.slug)}`);
  const slugProduct = await slugRes.json();
  console.log(`Retrieved Saree by Slug "${createdProd.slug}":`, slugProduct.name, `Price: $${slugProduct.priceUsd}`);

  console.log("\n=== 7. Inventory Stock Adjustment Check ===");
  const adjustRes = await fetch(`${BASE_URL}/api/admin/inventory/${encodeURIComponent(createdProd.id)}/adjust`, {
    method: "POST",
    headers: authHeaders,
    body: JSON.stringify({
      deltaQuantity: -2,
      reason: "Automated test deduction",
    }),
  });
  const adjustData = await adjustRes.json();
  console.log(`Stock adjusted: ${adjustData.previousStock} -> ${adjustData.newStock} (Product Stock: ${adjustData.product.stockQuantity})`);

  console.log("\n=== 8. Dynamic Categories Check ===");
  const catRes = await fetch(`${BASE_URL}/api/admin/categories`, { headers: authHeaders });
  const catData = await catRes.json();
  console.log(`Total Dynamic Categories: ${catData.categories.length}`);

  console.log("\n=== 9. Audit Logs Check ===");
  const auditRes = await fetch(`${BASE_URL}/api/admin/audit-logs?limit=5`, { headers: authHeaders });
  const auditData = await auditRes.json();
  console.log(`Recent Audit Actions Logged: ${auditData.logs.length}`);
  if (auditData.logs.length > 0) {
    console.log(`Latest: [${auditData.logs[0].action}] on [${auditData.logs[0].entityId}] by ${auditData.logs[0].user}`);
  }

  console.log("\n=== 10. Clean Up Test Saree ===");
  const delRes = await fetch(`${BASE_URL}/api/admin/products/${encodeURIComponent(createdProd.id)}?hard=true`, {
    method: "DELETE",
    headers: authHeaders,
  });
  const delData = await delRes.json();
  console.log("Cleanup Deleted Test Saree:", delData.success);

  console.log("\n==========================================");
  console.log("✅ ALL 10 MASTER CMS ACCEPTANCE TESTS PASSED!");
  console.log("==========================================");
}

runTests().catch((err) => {
  console.error("Test failed with error:", err);
  process.exit(1);
});
